walk:
    targets:
        - 
            - -0.0215
            -  0.85 
            - -1.2
            - 0.2
            - 0.0
            - -0.05
            - 0.1
        - 
            - -0.0215
            - -1.3 
            - 0.05
            - 0.2 
            - 0.0
            - -0.1
            - 0.2 
        -   
            - -0.0215 
            - 0.0 
            - -0.05 
            - 0.1 
            - 0.85
            - -1.2 
            - 0.2

        - 
            - -0.0215 
            - 0. 
            - -0.1 
            - 0.2 
            - -1.3
            - 0.05
            - 0.2
    
    kp:
        - 300
        - 390
        - 300
        - 300
        - 390
        - 300

    kd:
        - 30 
        - 39
        - 30
        - 30
        - 39
        - 30
    kp_torso: 480
    kd_torso: 240
    dt: 0.25
    c_d: 1.6
    c_v: 0
    mu: 0.65
    max_torque: 800
    g: -9.8

slow_run:
    targets:
        - 
            - -0.07
            -  1.3 
            - -1.75
            - 0.2
            - 0.0
            - -0.1
            - 0.1
        - 
            - -0.288
            - -2.1
            - -0.1
            - 0.2 
            - 0.0
            - -0.5
            - 0.2 
        -   
            - -0.07 
            - 0.0 
            - -0.1 
            - 0.1 
            - 1.3
            - -1.75 
            - 0.2

        - 
            - -0.288 
            - 0. 
            - -0.5 
            - 0.2 
            - -2.1
            - -0.1
            - 0.2
    
    kp:
        - 380
        - 450
        - 300
        - 380
        - 450
        - 300

    kd:
        - 37 
        - 41
        - 30
        - 37
        - 41
        - 30
    kp_torso: 450
    kd_torso: 140
    dt: 0.215
    c_d: 0
    c_v: 0.2
    mu: 0.65
    max_torque: 1000
    g: -9.8


jog:
    targets:
        - 
            - -0.07
            -  1.1 
            - -1.65
            - 0.2
            - 0.0
            - -0.1
            - 0.1
        - 
            - -0.288
            - -2.
            - -0.
            - 0.2 
            - 0.0
            - -0.5
            - 0.2 
        -   
            - -0.07 
            - 0.0 
            - -0.1 
            - 0.1 
            - 1.1
            - -1.65 
            - 0.2

        - 
            - -0.288 
            - 0. 
            - -0.5 
            - 0.2 
            - -2.
            - -0.
            - 0.2
    
    kp:
        - 500
        - 500
        - 500
        - 500
        - 500
        - 500

    kd:
        - 50
        - 50
        - 50
        - 50
        - 50
        - 50
    kp_torso: 450
    kd_torso: 160
    dt: 0.225
    c_d: 0.01
    c_v: 0.2
    mu: 0.65
    max_torque: 1000
    g: -9.8


run:
    targets:
        - 
            - -0.16
            -  .9 
            - -1.5
            - 0.2
            - 0.0
            - -0.1
            - 0.1
        - 
            - -0.4898
            - -3.
            - 0.1
            - 0.2 
            - 0.0
            - -0.5
            - 0.2 
        -   
            - -0.16 
            - 0.0 
            - -0.1 
            - 0.1 
            - .9
            - -1.5 
            - 0.2

        - 
            - -0.4898 
            - 0. 
            - -0.6 
            - 0.2 
            - -3.
            - 0.1
            - 0.2
    
    kp:
        - 720
        - 780
        - 700
        - 720
        - 780
        - 700

    kd:
        - 70
        - 70
        - 70
        - 70
        - 70
        - 70
    kp_torso: 800
    kd_torso: 80
    dt: 0.22
    c_d: 0.01
    c_v: 0.2
    mu: 0.65
    max_torque: 1000
    g: -9.8
test:
    targets:
        - 
            - -0.07
            -  1.1 
            - -1.65
            - 0.2
            - 0.0
            - -0.1
            - 0.1
        - 
            - -0.288
            - -2.
            - -0.
            - 0.2 
            - 0.0
            - -0.5
            - 0.2 
        -   
            - -0.07 
            - 0.0 
            - -0.1 
            - 0.1 
            - 1.1
            - -1.65 
            - 0.2

        - 
            - -0.288 
            - 0. 
            - -0.5 
            - 0.2 
            - -2.
            - -0.
            - 0.2
    
    kp:
        - 550
        - 600
        - 500
        - 550
        - 600
        - 500

    kd:
        - 50
        - 50
        - 50
        - 50
        - 50
        - 50
    kp_torso: 450
    kd_torso: 160
    dt: 0.225
    c_d: 0.01
    c_v: 0.2
    mu: 0.65
    max_torque: 1000
    g: -9.8


test2:
    targets:
        - 
            - -0.1999
            -  1.747 
            - -1.73
            - 0.30
            - 0.36
            - -0.44
            - 0.6689
        - 
            - -0.19999
            - -1.99
            - -1.224
            - 0.6172
            - -1.7875
            - -0.26672
            - -0.7906
        -   
            - -0.1999
            - 0.36 
            - -0.44
            - 0.6689
            - 1.747
            - -1.73 
            - 0.30

        - 
            - -0.1999
            - -1.7875
            -  -0.26672
            - -0.7906
            - -1.99
            - -1.224
            - 0.6172
    
    kp:
        - 500
        - 500
        - 500
        - 500
        - 500
        - 500

    kd:
        - 50
        - 50
        - 50
        - 50
        - 50
        - 50
    kp_torso: 500
    kd_torso: 50
    dt: 0.225
    c_d: 0.01
    c_v: 0.2
    mu: 0.65
    max_torque: 1000
    g: -9.8



